# Generated by Django 5.2.14 on 2026-05-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SdrObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_type', models.CharField(choices=[('AIS', 'AIS (navires)'), ('ADSB', 'ADS-B (aéronefs)'), ('APRS', 'APRS (stations)'), ('APRS Meteo', 'APRS Météo')], db_index=True, max_length=16, verbose_name='Type')),
                ('ident', models.CharField(db_index=True, max_length=64, verbose_name='Identifiant')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Nom')),
                ('lat', models.FloatField(verbose_name='Latitude')),
                ('lon', models.FloatField(verbose_name='Longitude')),
                ('speed', models.FloatField(blank=True, null=True, verbose_name='Vitesse')),
                ('heading', models.FloatField(blank=True, null=True, verbose_name='Cap')),
                ('altitude_ft', models.IntegerField(blank=True, null=True, verbose_name='Altitude (ft)')),
                ('mmsi', models.BigIntegerField(blank=True, null=True, verbose_name='MMSI')),
                ('icao', models.CharField(blank=True, max_length=8, verbose_name='ICAO')),
                ('temp_c', models.FloatField(blank=True, null=True, verbose_name='Température (°C)')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='Humidité (%)')),
                ('wind_dir', models.FloatField(blank=True, null=True, verbose_name='Direction vent (°)')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='Vent (km/h)')),
                ('wind_gust', models.FloatField(blank=True, null=True, verbose_name='Rafales (km/h)')),
                ('pressure_hpa', models.FloatField(blank=True, null=True, verbose_name='Pression (hPa)')),
                ('rain_mm', models.FloatField(blank=True, null=True, verbose_name='Pluie (mm)')),
                ('info', models.TextField(blank=True, verbose_name='Infos')),
                ('obs_date', models.CharField(blank=True, max_length=16)),
                ('obs_time', models.CharField(blank=True, max_length=16)),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='Données brutes')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='Première vue')),
                ('last_seen', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Dernière vue')),
            ],
            options={
                'verbose_name': 'Objet SDR',
                'verbose_name_plural': 'Objets SDR',
                'ordering': ('-last_seen',),
                'unique_together': {('obj_type', 'ident')},
            },
        ),
    ]
