# Generated by Django 5.2.14 on 2026-05-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SdrObjectTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_type', models.CharField(db_index=True, max_length=16)),
                ('ident', models.CharField(db_index=True, max_length=64)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('speed', models.FloatField(blank=True, null=True)),
                ('altitude_ft', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Position (trajet)',
                'verbose_name_plural': 'Positions (trajets)',
                'ordering': ('timestamp',),
                'indexes': [models.Index(fields=['obj_type', 'ident', 'timestamp'], name='map_sdrobje_obj_typ_4cf73c_idx')],
            },
        ),
    ]
