# Generated by Django 5.2.14 on 2026-05-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_sdrobjecttrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdrobject',
            name='obj_type',
            field=models.CharField(choices=[('AIS', 'AIS (navires)'), ('ADSB', 'ADS-B (aéronefs)'), ('APRS', 'APRS (stations)'), ('APRS Meteo', 'APRS Météo'), ('lrrp', 'LRRP / GPS DMR (DSD-FME)')], db_index=True, max_length=16, verbose_name='Type'),
        ),
    ]
