# Generated by Django 5.2.14 on 2026-05-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_sdrobject_obj_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdrobject',
            name='altitude_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Altitude (m)'),
        ),
        migrations.AddField(
            model_name='sdrobject',
            name='climb_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Vitesse verticale (m/s)'),
        ),
        migrations.AlterField(
            model_name='sdrobject',
            name='obj_type',
            field=models.CharField(choices=[('AIS', 'AIS (navires)'), ('ADSB', 'ADS-B (aéronefs)'), ('APRS', 'APRS (stations)'), ('APRS Meteo', 'APRS Météo'), ('lrrp', 'LRRP / GPS DMR (DSD-FME)'), ('radiosonde', 'Radiosonde')], db_index=True, max_length=16, verbose_name='Type'),
        ),
    ]
