# Generated by Django 5.2.14 on 2026-05-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_sdrobject_altitude_m_sdrobject_climb_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_type', models.CharField(choices=[('AIS', 'AIS (ships)'), ('ADSB', 'ADS-B (aircraft)'), ('APRS', 'APRS (stations)'), ('APRS Meteo', 'APRS weather'), ('lrrp', 'LRRP / DMR GPS (DSD-FME)'), ('radiosonde', 'Radiosonde')], max_length=16, unique=True)),
                ('minutes', models.PositiveIntegerField(default=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Retention setting',
                'verbose_name_plural': 'Retention settings',
                'ordering': ('obj_type',),
            },
        ),
        migrations.AlterModelOptions(
            name='sdrobject',
            options={'ordering': ('-last_seen',), 'verbose_name': 'SDR object', 'verbose_name_plural': 'SDR objects'},
        ),
        migrations.AlterModelOptions(
            name='sdrobjecttrack',
            options={'ordering': ('timestamp',), 'verbose_name': 'Track point', 'verbose_name_plural': 'Track points'},
        ),
        migrations.AlterField(
            model_name='sdrobject',
            name='climb_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Vertical speed (m/s)'),
        ),
        migrations.AlterField(
            model_name='sdrobject',
            name='extra',
            field=models.JSONField(blank=True, default=dict, verbose_name='Raw data'),
        ),
        migrations.AlterField(
            model_name='sdrobject',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True, verbose_name='First seen'),
        ),
        migrations.AlterField(
            model_name='sdrobject',
            name='heading',
            field=models.FloatField(blank=True, null=True, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='sdrobject',
            name='humidity',
            field=models.FloatField(blank=True, null=True, verbose_name='Humidity (%)'),
        ),
        migrations.AlterField(
            model_name='sdrobject',
            name='ident',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='sdrobject',
            name='info',
            field=models.TextField(blank=True, verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='sdrobject',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last seen'),
        ),
        migrations.AlterField(
            model_name='sdrobject',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sdrobject',
            name='obj_type',
            field=models.CharField(choices=[('AIS', 'AIS (ships)'), ('ADSB', 'ADS-B (aircraft)'), ('APRS', 'APRS (stations)'), ('APRS Meteo', 'APRS weather'), ('lrrp', 'LRRP / DMR GPS (DSD-FME)'), ('radiosonde', 'Radiosonde')], db_index=True, max_length=16, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='sdrobject',
            name='pressure_hpa',
            field=models.FloatField(blank=True, null=True, verbose_name='Pressure (hPa)'),
        ),
        migrations.AlterField(
            model_name='sdrobject',
            name='rain_mm',
            field=models.FloatField(blank=True, null=True, verbose_name='Rain (mm)'),
        ),
        migrations.AlterField(
            model_name='sdrobject',
            name='speed',
            field=models.FloatField(blank=True, null=True, verbose_name='Speed'),
        ),
        migrations.AlterField(
            model_name='sdrobject',
            name='temp_c',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperature (°C)'),
        ),
        migrations.AlterField(
            model_name='sdrobject',
            name='wind_dir',
            field=models.FloatField(blank=True, null=True, verbose_name='Wind direction (°)'),
        ),
        migrations.AlterField(
            model_name='sdrobject',
            name='wind_gust',
            field=models.FloatField(blank=True, null=True, verbose_name='Gust (km/h)'),
        ),
        migrations.AlterField(
            model_name='sdrobject',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True, verbose_name='Wind (km/h)'),
        ),
    ]
