# Generated by Django 5.2.14 on 2026-06-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_retentionsetting_alter_sdrobject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdrobject',
            name='ssi',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='SSI'),
        ),
        migrations.AlterField(
            model_name='retentionsetting',
            name='obj_type',
            field=models.CharField(choices=[('AIS', 'AIS (ships)'), ('ADSB', 'ADS-B (aircraft)'), ('APRS', 'APRS (stations)'), ('APRS Meteo', 'APRS weather'), ('lrrp', 'LRRP / DMR GPS (DSD-FME)'), ('radiosonde', 'Radiosonde'), ('TETRA', 'TETRA (LIP)')], max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='sdrobject',
            name='obj_type',
            field=models.CharField(choices=[('AIS', 'AIS (ships)'), ('ADSB', 'ADS-B (aircraft)'), ('APRS', 'APRS (stations)'), ('APRS Meteo', 'APRS weather'), ('lrrp', 'LRRP / DMR GPS (DSD-FME)'), ('radiosonde', 'Radiosonde'), ('TETRA', 'TETRA (LIP)')], db_index=True, max_length=16, verbose_name='Type'),
        ),
    ]
