# Generated by Django 5.2.14 on 2026-06-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_alter_retentionsetting_obj_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retentionsetting',
            name='obj_type',
            field=models.CharField(choices=[('AIS', 'AIS (ships)'), ('ADSB', 'ADS-B (aircraft)'), ('APRS', 'APRS (stations)'), ('APRS Meteo', 'APRS weather'), ('lrrp', 'LRRP / DMR GPS (DSD-FME)'), ('radiosonde', 'Radiosonde'), ('TETRA', 'TETRA (LIP)'), ('SARSAT', 'Cospas-Sarsat (406 MHz beacons)'), ('satellite', 'Satellites (orbital trackers)')], max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='sdrobject',
            name='obj_type',
            field=models.CharField(choices=[('AIS', 'AIS (ships)'), ('ADSB', 'ADS-B (aircraft)'), ('APRS', 'APRS (stations)'), ('APRS Meteo', 'APRS weather'), ('lrrp', 'LRRP / DMR GPS (DSD-FME)'), ('radiosonde', 'Radiosonde'), ('TETRA', 'TETRA (LIP)'), ('SARSAT', 'Cospas-Sarsat (406 MHz beacons)'), ('satellite', 'Satellites (orbital trackers)')], db_index=True, max_length=16, verbose_name='Type'),
        ),
    ]
